#
# Makefile for mrMesh
#
# 2003.05.07 Bob Dougherty
#

# wx-config --libs
WX_LIBS = $(shell /chroma/scr1/local/bin/wx-config --libs gl)
# wx-config --cxxflags
WX_CXXFLAGS = $(shell /chroma/scr1/local/bin/wx-config --cxxflags)

# Directories to search for header files
SEARCHDIRS := -iquote -I. -I/usr/include/vtk ${WX_CXXFLAGS}

# May want to add -O2 or -O3 and maybe -march=i686 for better performance
# -mfpmath=sse 	enables sse/sse2 for doubleing point operations
# -mmmx 	enables the mmx unit in Pentium II CPUs
# -msse 	enables the sse unit in Pentium III CPUs
# -msse2 	enables the sse2 unit in Pentium IV CPUs
# -msse-math 	enables math support via the sse unit in Pentium III and IV
# -m3dnow 	enables the 3dnow unit in Athlons
#DEPENDFLAGS := -Wall -Wno-deprecated -O3 -mcpu=i686 -march=i686 -msse -mfpmath=sse ${SEARCHDIRS}
DEPENDFLAGS := -Wall -Wno-deprecated -O3 ${SEARCHDIRS}
#DEPENDFLAGS := -Wall -g ${SEARCHDIRS}


# C preprocessor (C, C++, FORTRAN)
CPPFLAGS =  -DGTK_NO_CHECK_CASTS -D__WXGTK__ -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES

# C++ compiler
CXX      := g++ 
CXXFLAGS  = ${DEPENDFLAGS}

%.o : %.cc
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

%.o : %.C
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

%.o : %.cpp
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

%.o : %.cxx
	${CXX} ${CPPFLAGS} ${CXXFLAGS} -c $< -o $@

# C/C++/Eiffel/FORTRAN linker
#LINKER    := /usr/local/bin/gcc
LINKER    := gcc
LDFLAGS    := 
LIBS :=  \
-L/usr/lib -lstdc++ \
-L/usr/local/lib -pthread \
${WX_LIBS} \
-L/usr/X11R6/lib -lXi -lXext -lX11 -lXt \
-lGLU -lGL \
-L/usr/lib -lvtkRendering -lvtkGraphics -lvtkImaging -lvtkCommon -lvtkFiltering 

# mrMeshSrv
mrMeshSrv.glxa64 : ./3dview.o ./actor.o ./camera.o ./clientframe.o \
./commandhandler.o ./cursor.o ./doublearray.o ./grayVolume.o ./helpers.o \
./imagequad.o ./light.o ./matrix3x3.o ./mesh.o \
./mrmeshsrvapp.o ./parametersmap.o ./polydatabuffer.o ./polyline.o \
./progressindicator.o ./roi.o ./scene.o ./serverconsole.o ./stdafx.o \
./text.o ./transformarrow.o ./vtkfilter.o ./vtkPolyDataSingleSourceShortestPath.o
	${LINKER} ${LDFLAGS} -o $@ ${filter-out %.a %.so, $^} ${LIBS}

# target for making everything
all: mrMeshSrv.glxa64

# target for removing all object files
tidy: 
	@${RM} core ./*.o

# target for removing all object files and executable
clean: 
	@${RM} core ./*.o mrMeshSrv.glxa64
